package example.perf.util;

import com.beust.jcommander.Parameter;

import java.io.FileNotFoundException;
import java.io.PrintStream;

/**
 * Created by jackeylv on 2016/6/27.
 */
public class MarshallerParameters {

    @Parameter(names = "-dump", description = "HexDump the bytes array generated by marshaller.")
    public boolean dump = false;

    @Parameter(names = "-unmarshall", description = "Convert back the bytes array to objects or not.")
    public boolean unmarshall = false;

    @Parameter(names = {"-o", "--out"}, description = "Output file name")
    public String output_file = "statics.txt";

    @Parameter(names = {"-n", "--num"}, description = "Number of obejcts to be marshall or un-marshall.")
    public int num = 10000;

    @Parameter(names = {"-h", "--help"}, help = true, description = "Show the help message.")
    public boolean help = false;

    /** Output writer. */
    private transient PrintStream outputWriter;

    public PrintStream output() throws FileNotFoundException {
        if (null == outputWriter){
            outputWriter = new PrintStream(output_file);
        }
        return outputWriter;
    }

    @Override
    public String toString() {
        return "MarshallerParameters{" +
                "dump=" + dump +
                ", output file=" + output_file+
                ", unmarshall=" + unmarshall +
                ", num=" + num +
                '}';
    }
}
